import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import "../styles/ResumeReport.css";

function ResumeReport() {
  const { id } = useParams();
  const navigate = useNavigate();

  const [analysis, setAnalysis] = useState(null);
  const [loading, setLoading] = useState(true);
  const [downloading, setDownloading] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    fetchResumeReport();
  }, [id]);

  async function fetchResumeReport() {
    try {
      setLoading(true);
      setError("");

      const token = localStorage.getItem("token");

      if (!token) {
        throw new Error("Please log in to view this report.");
      }

      const response = await fetch(
        `http://https://ai-interview-platform-5e0s.onrender.com/api/resume/history/${id}`,
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );

      const data = await response.json();

      if (!response.ok) {
        throw new Error(
          data.message || "Unable to load the resume report."
        );
      }

      setAnalysis(data.analysis);
    } catch (err) {
      setError(
        err.message ||
          "Something went wrong while loading the report."
      );
    } finally {
      setLoading(false);
    }
  }

  function formatDate(date) {
    if (!date) {
      return "Unknown date";
    }

    return new Date(date).toLocaleDateString("en-IN", {
      day: "2-digit",
      month: "long",
      year: "numeric",
    });
  }

  function renderList(items, emptyMessage) {
    if (!Array.isArray(items) || items.length === 0) {
      return (
        <p className="resume-report-empty-text">
          {emptyMessage}
        </p>
      );
    }

    return (
      <ul className="resume-report-list">
        {items.map((item, index) => (
          <li key={`${item}-${index}`}>{item}</li>
        ))}
      </ul>
    );
  }

  function getAtsMessage(score) {
    if (score >= 80) {
      return "Strong ATS compatibility";
    }

    if (score >= 60) {
      return "Good resume with room for improvement";
    }

    return "Important ATS improvements are recommended";
  }

  function convertItemsToText(items, emptyMessage) {
    if (!Array.isArray(items) || items.length === 0) {
      return emptyMessage;
    }

    return items
      .map((item, index) => `${index + 1}. ${item}`)
      .join("\n");
  }

  function createSafeFileName(fileName) {
    const originalName = fileName || "resume";

    const withoutExtension = originalName.replace(
      /\.[^/.]+$/,
      ""
    );

    const safeName = withoutExtension
      .replace(/[^a-zA-Z0-9-_ ]/g, "")
      .trim()
      .replace(/\s+/g, "-");

    return safeName || "resume";
  }

  function addPageFooter(doc) {
    const totalPages = doc.internal.getNumberOfPages();

    for (let page = 1; page <= totalPages; page += 1) {
      doc.setPage(page);

      const pageWidth =
        doc.internal.pageSize.getWidth();

      const pageHeight =
        doc.internal.pageSize.getHeight();

      doc.setDrawColor(220, 220, 220);
      doc.line(15, pageHeight - 15, pageWidth - 15, pageHeight - 15);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(110, 110, 110);

      doc.text(
        "Generated by AI Interview Platform",
        15,
        pageHeight - 9
      );

      doc.text(
        `Page ${page} of ${totalPages}`,
        pageWidth - 15,
        pageHeight - 9,
        {
          align: "right",
        }
      );
    }
  }

  async function downloadPdfReport() {
    if (!analysis) {
      return;
    }

    try {
      setDownloading(true);

      const doc = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
      });

      const pageWidth =
        doc.internal.pageSize.getWidth();

      const atsScore = Number(
        analysis.atsScore || 0
      );

      const overallRating = Number(
        analysis.overallRating || 0
      );

      const interviewReadiness = Number(
        analysis.interviewReadinessScore || 0
      );

      doc.setFillColor(30, 64, 175);
      doc.rect(0, 0, pageWidth, 42, "F");

      doc.setTextColor(255, 255, 255);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(22);
      doc.text("AI Resume Analysis Report", 15, 18);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.text(
        analysis.fileName || "Resume",
        15,
        27
      );

      doc.text(
        `Analyzed on ${formatDate(
          analysis.createdAt
        )}`,
        15,
        34
      );

      autoTable(doc, {
        startY: 50,
        head: [
          [
            "ATS Score",
            "Overall Rating",
            "Interview Readiness",
          ],
        ],
        body: [
          [
            `${atsScore}%`,
            `${overallRating.toFixed(1)}/10`,
            `${interviewReadiness.toFixed(1)}/10`,
          ],
        ],
        theme: "grid",
        styles: {
          font: "helvetica",
          halign: "center",
          cellPadding: 5,
        },
        headStyles: {
          fillColor: [37, 99, 235],
          textColor: [255, 255, 255],
          fontStyle: "bold",
        },
        bodyStyles: {
          fontSize: 13,
          fontStyle: "bold",
          textColor: [30, 41, 59],
        },
      });

      let currentY =
        (doc.lastAutoTable?.finalY || 75) + 10;

      const sections = [
        {
          title: "ATS Assessment",
          content: getAtsMessage(atsScore),
        },
        {
          title: "Professional Summary",
          content:
            analysis.professionalSummary ||
            "No professional summary is available.",
        },
        {
          title: "Strengths",
          content: convertItemsToText(
            analysis.strengths,
            "No strengths were identified."
          ),
        },
        {
          title: "Weaknesses",
          content: convertItemsToText(
            analysis.weaknesses,
            "No major weaknesses were identified."
          ),
        },
        {
          title: "Missing Skills",
          content: convertItemsToText(
            analysis.missingSkills,
            "No missing skills were identified."
          ),
        },
        {
          title: "Improvement Suggestions",
          content: convertItemsToText(
            analysis.improvementSuggestions,
            "No improvement suggestions were provided."
          ),
        },
        {
          title: "Best Job Roles",
          content: convertItemsToText(
            analysis.bestJobRoles,
            "No job roles were recommended."
          ),
        },
        {
          title: "ATS Keyword Suggestions",
          content: convertItemsToText(
            analysis.keywordSuggestions,
            "No ATS keywords were suggested."
          ),
        },
      ];

      sections.forEach((section) => {
        const titleLines = doc.splitTextToSize(
          section.title,
          pageWidth - 30
        );

        const contentLines = doc.splitTextToSize(
          String(section.content),
          pageWidth - 34
        );

        const sectionHeight =
          titleLines.length * 7 +
          contentLines.length * 5 +
          12;

        const pageHeight =
          doc.internal.pageSize.getHeight();

        if (
          currentY + sectionHeight >
          pageHeight - 25
        ) {
          doc.addPage();
          currentY = 20;
        }

        doc.setFillColor(239, 246, 255);
        doc.roundedRect(
          15,
          currentY,
          pageWidth - 30,
          10,
          2,
          2,
          "F"
        );

        doc.setFont("helvetica", "bold");
        doc.setFontSize(12);
        doc.setTextColor(30, 64, 175);
        doc.text(
          titleLines,
          19,
          currentY + 6.5
        );

        currentY += 15;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.setTextColor(51, 65, 85);
        doc.text(
          contentLines,
          19,
          currentY,
          {
            lineHeightFactor: 1.45,
          }
        );

        currentY += contentLines.length * 5 + 10;
      });

      addPageFooter(doc);

      const safeFileName = createSafeFileName(
        analysis.fileName
      );

      doc.save(
        `${safeFileName}-AI-Resume-Report.pdf`
      );
    } catch (err) {
      console.error("PDF download error:", err);

      window.alert(
        "Unable to download the PDF report. Please try again."
      );
    } finally {
      setDownloading(false);
    }
  }

  if (loading) {
    return (
      <div className="resume-report-page">
        <div className="resume-report-loading">
          <div className="resume-report-spinner"></div>

          <h2>Loading resume report...</h2>

          <p>
            Please wait while we retrieve your saved
            analysis.
          </p>
        </div>
      </div>
    );
  }

  if (error || !analysis) {
    return (
      <div className="resume-report-page">
        <div className="resume-report-error-card">
          <div className="resume-report-error-icon">
            ⚠️
          </div>

          <h2>Unable to Open Report</h2>

          <p>
            {error || "Resume report not found."}
          </p>

          <button
            type="button"
            onClick={() =>
              navigate("/resume-history")
            }
          >
            Back to Resume History
          </button>
        </div>
      </div>
    );
  }

  const atsScore = Number(
    analysis.atsScore || 0
  );

  const overallRating = Number(
    analysis.overallRating || 0
  );

  const interviewReadiness = Number(
    analysis.interviewReadinessScore || 0
  );

  return (
    <div className="resume-report-page">
      <div className="resume-report-container">
        <div className="resume-report-topbar">
          <button
            type="button"
            className="resume-report-back-button"
            onClick={() =>
              navigate("/resume-history")
            }
          >
            ← Back to History
          </button>

          <button
            type="button"
            className="resume-report-new-button"
            onClick={downloadPdfReport}
            disabled={downloading}
          >
            {downloading
              ? "Creating PDF..."
              : "Download PDF"}
          </button>

          <button
            type="button"
            className="resume-report-new-button"
            onClick={() =>
              navigate("/resume-analyzer")
            }
          >
            Analyze New Resume
          </button>
        </div>

        <header className="resume-report-header">
          <div className="resume-report-file-heading">
            <span className="resume-report-file-icon">
              📄
            </span>

            <div>
              <p className="resume-report-label">
                AI Resume Report
              </p>

              <h1>{analysis.fileName}</h1>

              <p>
                Analyzed on{" "}
                {formatDate(analysis.createdAt)}
              </p>
            </div>
          </div>

          <span className="resume-report-reviewed-badge">
            AI Reviewed
          </span>
        </header>

        <section className="resume-report-score-grid">
          <article className="resume-report-score-card ats-score-card">
            <p>ATS Score</p>

            <h2>{atsScore}%</h2>

            <div className="resume-report-progress">
              <div
                className="resume-report-progress-fill"
                style={{
                  width: `${Math.min(
                    Math.max(atsScore, 0),
                    100
                  )}%`,
                }}
              ></div>
            </div>

            <span>
              {getAtsMessage(atsScore)}
            </span>
          </article>

          <article className="resume-report-score-card">
            <p>Overall Rating</p>

            <h2>
              {overallRating.toFixed(1)}/10
            </h2>

            <span>Overall resume quality</span>
          </article>

          <article className="resume-report-score-card">
            <p>Interview Readiness</p>

            <h2>
              {interviewReadiness.toFixed(1)}/10
            </h2>

            <span>
              Current interview preparation level
            </span>
          </article>
        </section>

        <section className="resume-report-summary-card">
          <div className="resume-report-card-title">
            <span>🧑‍💼</span>
            <h2>Professional Summary</h2>
          </div>

          <p>
            {analysis.professionalSummary ||
              "No professional summary is available."}
          </p>
        </section>

        <section className="resume-report-content-grid">
          <article className="resume-report-content-card strengths-report-card">
            <div className="resume-report-card-title">
              <span>✅</span>
              <h2>Strengths</h2>
            </div>

            {renderList(
              analysis.strengths,
              "No strengths were identified."
            )}
          </article>

          <article className="resume-report-content-card weaknesses-report-card">
            <div className="resume-report-card-title">
              <span>⚠️</span>
              <h2>Weaknesses</h2>
            </div>

            {renderList(
              analysis.weaknesses,
              "No major weaknesses were identified."
            )}
          </article>

          <article className="resume-report-content-card skills-report-card">
            <div className="resume-report-card-title">
              <span>🛠️</span>
              <h2>Missing Skills</h2>
            </div>

            {renderList(
              analysis.missingSkills,
              "No missing skills were identified."
            )}
          </article>

          <article className="resume-report-content-card suggestions-report-card">
            <div className="resume-report-card-title">
              <span>📈</span>
              <h2>Improvement Suggestions</h2>
            </div>

            {renderList(
              analysis.improvementSuggestions,
              "No improvement suggestions were provided."
            )}
          </article>

          <article className="resume-report-content-card roles-report-card">
            <div className="resume-report-card-title">
              <span>💼</span>
              <h2>Best Job Roles</h2>
            </div>

            {renderList(
              analysis.bestJobRoles,
              "No job roles were recommended."
            )}
          </article>

          <article className="resume-report-content-card keywords-report-card">
            <div className="resume-report-card-title">
              <span>🔑</span>
              <h2>ATS Keywords</h2>
            </div>

            {Array.isArray(
              analysis.keywordSuggestions
            ) &&
            analysis.keywordSuggestions.length >
              0 ? (
              <div className="resume-report-keywords">
                {analysis.keywordSuggestions.map(
                  (keyword, index) => (
                    <span
                      key={`${keyword}-${index}`}
                    >
                      {keyword}
                    </span>
                  )
                )}
              </div>
            ) : (
              <p className="resume-report-empty-text">
                No ATS keywords were suggested.
              </p>
            )}
          </article>
        </section>
      </div>
    </div>
  );
}

export default ResumeReport;